name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
  
    - name: Geração do pacote
      run: dotnet build -c Release -o out
    
    - name: Push no NuGet
      run: |
        cd out
        nuget source Add -Name "github1" -Source "https://nuget.pkg.github.com/julioarruda/index.json"
        nuget setApiKey ${{ secrets.GITHUB_TOKEN }} -Source "https://nuget.pkg.github.com/julioarruda/index.json"
        dotnet nuget push *.nupkg --source "github1" --skip-duplicate

